spring.application.name=github-proxy
spring.cloud.openfeign.client.config.github-proxy.url=https://api.github.com
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=username
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method
logging.level.org.hibernate.SQL=INFO